<a href="https://colab.research.google.com/github/2303a52274/STML-2303A52274/blob/main/2303A52274_sml_project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
d=pd.read_csv("/content/Employee_Salary_Dataset.csv")
print(d.head())


   ID  Experience_Years  Age  Gender  Salary
0   1                 5   28  Female  250000
1   2                 1   21    Male   50000
2   3                 3   23  Female  170000
3   4                 2   22    Male   25000
4   5                 1   17    Male   10000


In [2]:
X=d.drop(['Salary','ID'],axis=1)
mle_params={}
y=d["Salary"]
print("target:")
print(y.head())
print("shape:",y.shape)
print("features:")
print(X.head())

target:
0    250000
1     50000
2    170000
3     25000
4     10000
Name: Salary, dtype: int64
shape: (35,)
features:
   Experience_Years  Age  Gender
0                 5   28  Female
1                 1   21    Male
2                 3   23  Female
3                 2   22    Male
4                 1   17    Male


In [3]:
S=X.replace({'Female':0,'Male':1,'Yes':1,'No':0})
print(S.head())

   Experience_Years  Age  Gender
0                 5   28       0
1                 1   21       1
2                 3   23       0
3                 2   22       1
4                 1   17       1


<ipython-input-3-e71453c97105>:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  S=X.replace({'Female':0,'Male':1,'Yes':1,'No':0})


In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(S, y , test_size=0.2, random_state=30)
print("X_train:",X_train)
print("X_test:",X_test)
print("Y_train:",y_train)
print("Y_train:",y_test)

X_train:     Experience_Years  Age  Gender
24                 4   23       0
32                20   55       0
4                  1   17       1
25                 3   22       0
31                15   54       1
15                 4   27       0
11                 6   29       1
22                 5   29       1
0                  5   28       0
34                16   49       1
6                 19   54       0
19                10   36       1
18                 2   21       1
30                10   34       1
13                11   40       1
29                 2   21       0
1                  1   21       1
33                19   53       0
7                  2   21       0
9                 15   54       0
3                  2   22       1
14                 2   23       1
17                15   54       0
27                27   62       0
21                 4   26       1
2                  3   23       0
23                 1   21       0
12                14   39       1
X_tes

In [5]:
from sklearn.linear_model import LinearRegression
RR= LinearRegression()
mm=RR.fit(X_train, y_train)
print(mm.intercept_)
print(mm.coef_)

1101424.2768121592
[ 496868.42595833 -103740.63915749  324544.08457495]


In [6]:
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import root_mean_squared_error
print(mean_squared_error(y_train,mm.predict(X_train)))
print(mean_absolute_error(y_train,mm.predict(X_train)))
print(root_mean_squared_error(y_train,mm.predict(X_train)))
print(mean_squared_error(y_test,mm.predict(X_test)))
print(mean_absolute_error(y_test,mm.predict(X_test)))
print(root_mean_squared_error(y_test,mm.predict(X_test)))


5683490222262.789
1650606.2537520735
2384007.1774771963
3496242708463.1187
1406978.3239479437
1869824.2453404863


In [7]:
from sklearn.svm import SVR
ss= SVR()
sv=ss.fit(X_train, y_train)
print(sv.intercept_)

[195052.29414782]


In [8]:
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import root_mean_squared_error
print(mean_squared_error(y_train,sv.predict(X_train)))
print(mean_absolute_error(y_train,sv.predict(X_train)))
print(root_mean_squared_error(y_train,sv.predict(X_train)))
print(mean_squared_error(y_test,sv.predict(X_test)))
print(mean_absolute_error(y_test,sv.predict(X_test)))
print(root_mean_squared_error(y_test,sv.predict(X_test)))


13424499134498.268
1900553.967635239
3663945.842189574
12488895425177.576
2443045.724171244
3533963.132968081


In [9]:
from sklearn.linear_model import Lasso
cc= Lasso()
lr=cc.fit(X_train, y_train)
print(lr.intercept_)
print(lr.coef_)

1101422.3199359574
[ 496867.86116467 -103740.38065829  324539.91108861]


In [10]:
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import root_mean_squared_error
print(mean_squared_error(y_train,lr.predict(X_train)))
print(mean_absolute_error(y_train,lr.predict(X_train)))
print(root_mean_squared_error(y_train,lr.predict(X_train)))
print(mean_squared_error(y_test,lr.predict(X_test)))
print(mean_absolute_error(y_test,lr.predict(X_test)))
print(root_mean_squared_error(y_test,lr.predict(X_test)))


5683490222267.796
1650606.2715809639
2384007.1774782464
3496242099843.1606
1406978.1092525278
1869824.082592574


In [11]:
from sklearn.linear_model import Ridge
tt= Ridge()
rr=tt.fit(X_train, y_train)
print(rr.intercept_)
print(rr.coef_)

1070820.2093359465
[ 489762.64966352 -100461.96148068  282195.18694048]


In [13]:
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import root_mean_squared_error
print(mean_squared_error(y_train,lr.predict(X_train)))
print(mean_absolute_error(y_train,lr.predict(X_train)))
print(root_mean_squared_error(y_train,lr.predict(X_train)))
print(mean_squared_error(y_test,lr.predict(X_test)))
print(mean_absolute_error(y_test,lr.predict(X_test)))
print(root_mean_squared_error(y_test,lr.predict(X_test)))


5683490222267.796
1650606.2715809639
2384007.1774782464
3496242099843.1606
1406978.1092525278
1869824.082592574


In [15]:
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import mean_squared_error
knn = KNeighborsRegressor(n_neighbors=5)
knn.fit(X_train, y_train)
print(mean_squared_error(y_train,knn.predict(X_train)))
print(mean_squared_error(y_test,knn.predict(X_test)))


6078088202753.571
1586714761514.2856
